<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sign Up</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="../css/signin.css" rel="stylesheet">
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../js/ie10-viewport-bug-workaround.js"></script>
<script src="../bower_components/jquery/dist/jquery.js"></script>
<script src="../js/main.js"></script>
</head>

<body>

<div class="container">

    <form class="form-signin">
        <h2 class="form-signin-heading">Sign Up</h2>
        <label for="username" class="sr-only">Username</label>
        <input type="text" id="username" class="form-control" placeholder="username" required autofocus>
        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" class="form-control" placeholder="Password" required autofocus>
        <label for="input-accountType" class="sr-only">Account Type</label>
        <select id="accountType" name="accountType" class="form-control">
							<option value="0">Choose Account Type</option>
                            <option value="1">Student</option>
                            <option value="2">Administrator</option>
		</select>
        <input class="btn btn-lg btn-primary btn-block" type="button" id="signupBtn" value="Sign Up">
        <a class="btn btn-lg btn-primary btn-block" href="index.php">Login</a>
    </form>

    <div id="resp"></div>
</div> <!-- /container -->

</body>
</html>
