<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sign Up</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="../css/signin.css" rel="stylesheet">
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../js/ie10-viewport-bug-workaround.js"></script>
<script src="../bower_components/jquery/dist/jquery.js"></script>
<script src="../js/main.js"></script>
</head>

<body>

<div class="container">

    <form class="form-signin">
        <h2 class="form-signin-heading">Forgot Your Password?</h2>
        <label for="username" class="sr-only">Enter Email address</label>
        <input type="email" id="email" class="form-control" placeholder="Email Address" required autofocus>
        <a class="btn btn-lg btn-primary btn-block" href="index.php">Submit</a>
    </form>

    <div id="resp"></div>
</div> <!-- /container -->

</body>
</html>